const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');
const CatchShare = require('./CatchShare');

const CatchSensor = sequelize.define('CatchSensor', {
    id: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        primaryKey: true,
    },
    name: {
        type: DataTypes.STRING,
        allowNull: false,
    },
    alias: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    location: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    type: {
        type: DataTypes.ENUM('NB-IOT', 'LORAWAN'),
        defaultValue: 'NB-IOT',
    },
    imei: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    deviceId: {
        type: DataTypes.STRING,
        allowNull: true,
    },
    status: {
        type: DataTypes.ENUM('active', 'inactive', 'triggered'),
        defaultValue: 'inactive',
    },
    batteryVoltage: {
        type: DataTypes.INTEGER,
        allowNull: true,
    },
    batteryPercent: {
        type: DataTypes.INTEGER,
        allowNull: true,
    },
    rsrp: {
        type: DataTypes.INTEGER,
        allowNull: true,
    },
    lastSeen: {
        type: DataTypes.DATE,
        allowNull: true,
    },
    batteryThreshold: {
        type: DataTypes.INTEGER,
        allowNull: true,
    },
    lastBatteryAlert: {
        type: DataTypes.DATE,
        allowNull: true,
    },
    lastOfflineAlert: {
        type: DataTypes.DATE,
        allowNull: true,
    },
    lastCatchAlert: {
        type: DataTypes.DATE,
        allowNull: true,
    },
    alarmAcknowledgedAt: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: 'Set when user acknowledges an alarm. Cleared when a new trigger event arrives.'
    },
    userId: {
        type: DataTypes.UUID,
        allowNull: true,
    },
    revierweltWebhookUrl: {
        type: DataTypes.STRING,
        allowNull: true,
        comment: 'Optional Revierwelt Webhook URL'
    },
    lastFCnt: {
        type: DataTypes.BIGINT,
        defaultValue: 0,
        comment: 'Last received message counter for replay protection'
    },
    resyncRequired: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        comment: 'Set when a lower counter is detected (potential battery reset)'
    },
    claimingPin: {
        type: DataTypes.STRING(10),
        allowNull: true,
        comment: 'Individual PIN for initial device registration (from QR code)'
    },
    aesKey: {
        type: DataTypes.STRING(64),
        allowNull: true,
        comment: 'Individual AES-256 key (Hex) generated by device during handshake'
    },
    isProvisioned: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        comment: 'True if individual AES key handshake is complete'
    }
}, {
    tableName: 'CatchSensors',
    timestamps: true,
    indexes: [
        { unique: true, fields: ['imei'] },
        { unique: true, fields: ['deviceId'] },
        { fields: ['userId'] },
        { fields: ['type'] },
        { fields: ['status'] }
    ]
});

CatchSensor.hasMany(CatchShare, { foreignKey: 'catchSensorId', onDelete: 'CASCADE' });
CatchShare.belongsTo(CatchSensor, { foreignKey: 'catchSensorId', onDelete: 'CASCADE' });

module.exports = CatchSensor;

