[env:stm32l0]
platform = ststm32
board = nucleo_l053r8
framework = arduino
monitor_speed = 115200
build_flags = 
	-D STM32L0
	-D CONFIG_PATH=include/config.h

[env:stm32l4]
platform = ststm32
board = nucleo_l432kc
framework = arduino
monitor_speed = 115200
build_flags = 
	-D STM32L4
	-D CONFIG_PATH=include/config.h
